# Generated by Django 6.0.4 on 2026-04-22 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_sector"),
    ]

    operations = [
        migrations.CreateModel(
            name="Fleet",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("power", models.IntegerField(default=100)),
                ("status", models.CharField(default="Operacional", max_length=50)),
            ],
        ),
    ]
