# Generated by Django 6.0.4 on 2026-04-22 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_fleet"),
    ]

    operations = [
        migrations.AddField(
            model_name="sector",
            name="colonized",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="sector",
            name="owner",
            field=models.CharField(blank=True, default="", max_length=100),
        ),
    ]
