# Generated by Django 6.0.4 on 2026-04-24 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_sector_colonized_sector_owner"),
    ]

    operations = [
        migrations.CreateModel(
            name="Leader",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("role", models.CharField(max_length=100)),
                ("bonus", models.CharField(max_length=200)),
                ("active", models.BooleanField(default=False)),
            ],
        ),
    ]
