# Generated by Django 6.0.4 on 2026-04-24 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0006_leader"),
    ]

    operations = [
        migrations.AddField(
            model_name="faction",
            name="military",
            field=models.IntegerField(default=10),
        ),
    ]
