# Generated by Django 6.0.4 on 2026-04-24 23:23

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("turns", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="turn",
            name="number",
            field=models.IntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name="turn",
            name="processed_at",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
