# Generated by Django 6.0.4 on 2026-04-21 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Commander",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("fuel", models.IntegerField(default=1000)),
                ("minerals", models.IntegerField(default=500)),
                ("science", models.IntegerField(default=0)),
                ("morale", models.IntegerField(default=100)),
                ("reputation", models.IntegerField(default=50)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
